//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelStationManagementSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuelStationManagementSystem.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Customer (ID, [Name], Surname, CardNumber) 
        ///VALUES (NEWID(), &apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;).
        /// </summary>
        internal static string QAddCustomer {
            get {
                return ResourceManager.GetString("QAddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Employee (ID, [Name], Surname, DateStart, Salary) 
        ///VALUES (NEWID(), &apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;, &apos;{3}&apos;).
        /// </summary>
        internal static string QAddEmployee {
            get {
                return ResourceManager.GetString("QAddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Items (ID, Code, [Description], ItemType, Price, Cost) 
        ///VALUES(NEWID(), &apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;, {3}, {4}, {5}).
        /// </summary>
        internal static string QAddItem {
            get {
                return ResourceManager.GetString("QAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Transaction](ID, Date, CustomerID, DiscountValue, TotalValue, TotalCost) 
        ///VALUES(&apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;, {3}, {4}, {5}).
        /// </summary>
        internal static string QAddTransaction {
            get {
                return ResourceManager.GetString("QAddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TransactionLine (ID, TransactionID, ItemID, Quantity, ItemPrice, [Value], ItemCost, Cost, ItemType) 
        ///VALUES (&apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;, {3}, {4}, {5}, {6}, {7}, &apos;{8}&apos;).
        /// </summary>
        internal static string QAddTransactionLines {
            get {
                return ResourceManager.GetString("QAddTransactionLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Customer WHERE CardNumber = &apos;{0}&apos;.
        /// </summary>
        internal static string QDeleteCustomer {
            get {
                return ResourceManager.GetString("QDeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Employee WHERE ID = &apos;{0}&apos;.
        /// </summary>
        internal static string QDeleteEmployee {
            get {
                return ResourceManager.GetString("QDeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Employee 
        ///SET DateEnd= &apos;{0}&apos;
        ///WHERE ID = &apos;{1}&apos;.
        /// </summary>
        internal static string QDismissEmployee {
            get {
                return ResourceManager.GetString("QDismissEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Customer 
        ///SET [Name]= &apos;{0}&apos; ,Surname = &apos;{1}&apos; 
        ///WHERE CardNumber = &apos;{2}&apos;.
        /// </summary>
        internal static string QEditCustomer {
            get {
                return ResourceManager.GetString("QEditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Employee 
        ///SET [Name]= &apos;{0}&apos;, Surname=&apos;{1}&apos;, Salary=&apos;{2}&apos;
        ///WHERE ID = &apos;{3}&apos;.
        /// </summary>
        internal static string QEditEmployee {
            get {
                return ResourceManager.GetString("QEditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Employee (ID, [Name], Surname, DateStart, Salary) 
        ///VALUES (NEWID(), &apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;, &apos;{3}&apos;).
        /// </summary>
        internal static string QLedgerPay {
            get {
                return ResourceManager.GetString("QLedgerPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Customer.
        /// </summary>
        internal static string QPopulateCustomer {
            get {
                return ResourceManager.GetString("QPopulateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Employee.
        /// </summary>
        internal static string QPopulateEmployee {
            get {
                return ResourceManager.GetString("QPopulateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID, Code, [Description], ItemType, Price, Cost FROM Items.
        /// </summary>
        internal static string QPopulateItem {
            get {
                return ResourceManager.GetString("QPopulateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM  Items.
        /// </summary>
        internal static string QPopulateTransaction {
            get {
                return ResourceManager.GetString("QPopulateTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Items WHERE ItemType= &apos;{0}&apos;.
        /// </summary>
        internal static string QTransactionFilterByItem {
            get {
                return ResourceManager.GetString("QTransactionFilterByItem", resourceCulture);
            }
        }
    }
}
